# MPLAB IDE generated this makefile for use with GNU make.
# Project: Practica3.mcp
# Date: Wed Mar 02 22:09:49 2022

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

Plantilla_3.cof : Plantilla_3.o
	$(CC) /p16F887 "Plantilla_3.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"Plantilla_3.cof" /M"Plantilla_3.map" /W /x

Plantilla_3.o : Plantilla_3.ASM ../../../../../Program\ Files\ (x86)/Microchip/MPASM\ Suite/p16f887.inc
	$(AS) /q /p16F887 "Plantilla_3.ASM" /l"Plantilla_3.lst" /e"Plantilla_3.err" /d__DEBUG=1

clean : 
	$(CC) "Plantilla_3.o" "Plantilla_3.hex" "Plantilla_3.err" "Plantilla_3.lst" "Plantilla_3.cof"

