import java.util.Random;
import java.util.Arrays;
public class Principal extends javax.swing.JFrame {

    
    int []indices=null,indicesAcruzar=null;
    Random random = new Random();
    int  tamanoPoblacion;
    int numeroDeGeneraciones;
    int totalIndices;
    String palabra;
    String [] pobla=null,  nuevaPoblacion=null, elmejor1=null;
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingresa la palabra");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Numero de la poblacion");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numero de generaciones");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(71, 71, 71))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButton1)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jTextArea1.append("LA PALABRA A BUSCAR:   ");
        jTextArea1.append(jTextField1.getText());
        jTextArea1.append("\n"+"_______________________________________________");
        tamanoPoblacion  = Integer.parseInt(jTextField2.getText());
        numeroDeGeneraciones =Integer.parseInt(jTextField3.getText());
        crearPoblacion();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public String Individuo(){
        String alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz°!#$%&/()=?¡*;:_-<>{}[]\"";
        StringBuilder sb = new StringBuilder();
        for(int i = 0; i < jTextField1.getText().length(); i++) {
        int index = random.nextInt(alphabet.length());
        char randomChar = alphabet.charAt(index);
        sb.append(randomChar);
        }
        String nombre=sb.toString();
        System.out.println("individuo: "+nombre);
        return nombre;
    }
    public void crearPoblacion(){
            elmejor1= new String[numeroDeGeneraciones];
            pobla= new String[tamanoPoblacion];
            for(int j=0;j<tamanoPoblacion;j++){
                pobla[j]=Individuo();
            }
            
            for(int j=0;j< numeroDeGeneraciones;j++){
                System.out.println("------------------------------------------------");
                aptitud(pobla);
                jTextArea1.append("\n"+"El mejor de la generacion "+j+" es : "+pobla[elmejor()]);
                jTextArea1.append("\n");
                elmejor1[j]=pobla[elmejor()];
            }
              jTextArea1.append("\n"+"mejor de los mejores:");
              jTextArea1.append("\n"+"Generacion: " +elmejorMejor() );
              jTextArea1.append("\n"+"Palabra: " +  elmejor1[elmejorMejor()]);
             
    }
    public void aptitud(String [] pobla){
            int aux=0;
            int a=0;
            palabra=jTextField1.getText();
            indices=new int[tamanoPoblacion];
            for(int j=0;j<tamanoPoblacion;j++){
                for(int i=0;i<jTextField1.getText().length();i++){
                    if( palabra.charAt(i)==pobla[j].charAt(i)){
                        aux++;
                    }
                for(int k=0;k<jTextField1.getText().length();k++){
                    if( palabra.charAt(i)==pobla[j].charAt(k)){
                        aux+=1;
                    }  
                }
            }
         a=a+aux;
         totalIndices=a;
         indices [j]=aux;
         aux=0;
         //System.out.println(pobla[j]+" valores en el indice:"+indices[j]);
       }
       //System.out.println("total: "+totalIndices);
        seleccion();
       
        
    }
    public void seleccion(){
        int aux4=0,k=0,c=0;
        indicesAcruzar=new int[tamanoPoblacion];
        for(int j=0;j<tamanoPoblacion;j++){
            int numeroAlatorio = (int) Math.floor(Math.random()*(totalIndices)+1);
           // System.out.println("Valor de la ruleta:"+numeroAlatorio);
            if(totalIndices!=0){
                for(int i=0;i<tamanoPoblacion;i++){
                    if((indices[i]+aux4)<numeroAlatorio){
                        aux4=aux4+indices[i];}   
                    else if((indices[i]+aux4)>=numeroAlatorio){
                     // System.out.println("IndividioM: "+i);
                        c=i;
                    break; 
                    }
                } 
            }else if(totalIndices==0){
                 //System.out.println("Individio: "+0);
            }
                indicesAcruzar[k]=c;//guarda los indices de los individuos a cruzar
                k++;
                aux4=0;
        }     
        cruza();
    }
    public void cruza(){
       String c1,c2;
       nuevaPoblacion=new String[tamanoPoblacion];
       for (int i=0;i<tamanoPoblacion;i++){
            // System.out.println("papa:"+pobla[ indicesAcruzar[i]]);
            // System.out.println("mama:"+pobla[ indicesAcruzar[i+1]]);
              c1=hijo1(i);
              nuevaPoblacion[i]=c1;
              c2=hijo2(i);
              nuevaPoblacion[i+1]=c2;
              i++;
       }
             //System.out.println("------------------------------------------------------");
             //System.out.println("Poblacion cruzada");
             prueba(nuevaPoblacion);
              mutar();
    }
    public void prueba(String []  nuevaPoblacion){
        
        for(int i=0;i<tamanoPoblacion;i++){
           //System.out.println("Nueva Poblacion:"+  nuevaPoblacion[i]);
        }
    }
    public void mutar(){
        String alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz°!#$%&/()=?¡*;:_-<>{}[]\"";
        for (int i=0;i<(tamanoPoblacion*0.2);i++){
            int mutar=random.nextInt(pobla.length);
            int l1=random.nextInt( nuevaPoblacion[mutar].length());
            String array=String.valueOf( nuevaPoblacion[mutar].charAt(l1));
            int l2=random.nextInt(alphabet.length());
            String array2=String.valueOf(alphabet.charAt(l2));
            String ne =  nuevaPoblacion[mutar].replace(array, array2);
            nuevaPoblacion[mutar]=ne;
        }
       //  System.out.println("------------------------------------------------------");
         //System.out.println("Nueva poblacion");
         prueba(nuevaPoblacion);
        pobla = Arrays.copyOf(nuevaPoblacion, nuevaPoblacion.length);
       
    }
    public int elmejor(){
            int aux=0;
            int a=0;
            int w=0;
            for(int j=0;j<tamanoPoblacion;j++){
                for(int i=0;i<jTextField1.getText().length();i++){
                    if( palabra.charAt(i)==pobla[j].charAt(i)){
                        aux++;
                    }
                for(int k=0;k<jTextField1.getText().length();k++){
                    if( palabra.charAt(i)==pobla[j].charAt(k)){
                        aux+=1;
                    }  
                }
            }
            if(aux>a){
            w=j;
            a=aux;}
         aux=0;
         
       }
        return w;
    }
    
      public int elmejorMejor(){
            int aux=0;
            int a=0;
            int w=0;
            for(int j=0;j<tamanoPoblacion;j++){
                for(int i=0;i<jTextField1.getText().length();i++){
                    if( palabra.charAt(i)==elmejor1[j].charAt(i)){
                        aux++;
                    }
                for(int k=0;k<jTextField1.getText().length();k++){
                    if( palabra.charAt(i)==elmejor1[j].charAt(k)){
                        aux+=1;
                    }  
                }
            }
            if(aux>a){
            w=j;
            a=aux;}
         aux=0;
         
       }
        return w;
    }
    public String hijo1(int k){
         int valor =(jTextField1.getText().length()-1);
         String primera =pobla[ indicesAcruzar[k]].substring(0,valor/2);
         String segunda =pobla[ indicesAcruzar[k+1]].substring(valor/2,valor);
         String tercera =pobla[ indicesAcruzar[k]].substring(valor,jTextField1.getText().length());
        return primera+segunda+tercera;
    }
    public String hijo2(int k){
        int valor =(jTextField1.getText().length()-1);
        System.out.println("muestra: "+valor);
        String primera =pobla[ indicesAcruzar[k]].substring(valor/2,valor);
        String segunda =pobla[ indicesAcruzar[k+1]].substring(0,valor/2);
        String tercera =pobla[ indicesAcruzar[k]].substring(valor,jTextField1.getText().length());
        return segunda+primera+tercera;
        
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
